"""Type stubs for pandas DataFrame."""
from typing import Any, Dict, List, Literal, Optional, Union, overload

class DataFrame:
    @overload
    def to_dict(self, orient: Literal["records"]) -> List[Dict[str, Any]]: ...
    
    @overload
    def to_dict(self, orient: Literal["dict", "list", "series", "split", "index"] = "dict") -> Dict[str, Any]: ...
    
    def to_dict(self, orient: str = "dict") -> Union[Dict[str, Any], List[Dict[str, Any]]]: ...
    
    def __getitem__(self, key: Union[str, List[str]]) -> "DataFrame": ...
    
    def __setitem__(self, key: str, value: Any) -> None: ... 