"""Type stubs for pytest."""
from typing import Any, Callable, Optional, TypeVar

T = TypeVar('T')

def fixture(scope: str = "function", autouse: bool = False, params: Any = None, ids: Any = None, name: Optional[str] = None) -> Callable[[T], T]: ...
def mark(name: str, *args: Any, **kwargs: Any) -> Any: ...
def raises(expected_exception: Any, *args: Any, **kwargs: Any) -> Any: ... 