"""Type stubs for slack_sdk.errors."""
from typing import Any, Dict, Optional

class SlackApiError(Exception):
    def __init__(
        self,
        response: Optional[Dict[str, Any]] = None,
        message: str = "",
    ) -> None: ...
    @property
    def response(self) -> Dict[str, Any]: ...

class SlackClientError(Exception): ...
class SlackClientNotConnectedError(SlackClientError): ...
class SlackObjectFormationError(Exception): ...
class SlackRequestError(Exception): ...
class SlackTokenRotationError(Exception): ... 